# Generated by Django 5.0 on 2023-12-31 13:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='seconds',
            field=models.PositiveSmallIntegerField(default=180, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3600)]),
        ),
    ]
