# Generated by Django 5.0 on 2023-12-28 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizApp', '0004_alter_answer_question_alter_question_quiz_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='date_updated',
        ),
        migrations.RemoveField(
            model_name='question',
            name='date_updated',
        ),
    ]
